const data = [
    {
        "id": 1,
        "event": "Заявление",
        "title": "Результат для студента 4 курса",
        "note": "Для магистратуры",
        "group": "8191-21",
        "solved": 0,
        "name": "Валериана Любимова",
        "year": "3",
        "telephone": "+7 903 801 2899",
        "id_vk": null,
        "linkVK": "http://vk.com/Garth",
        "email": "ValerianVolkov6@hotmail.com",
        "created_at": "2023-06-01T14:38:37.000Z"
    },
    {
        "id": 2,
        "event": "Результат",
        "title": "Заявление 1",
        "note": "Для справки",
        "group": "8191-22",
        "solved": 0,
        "name": "Игорь Галкина",
        "year": "1",
        "telephone": "+7 903 086 5977",
        "id_vk": null,
        "linkVK": "http://vk.com/Sabryna",
        "email": "IgorGalkina@yahoo.com",
        "created_at": "2023-06-01T14:38:37.000Z"
    },
    {
        "id": 3,
        "event": "Заявление",
        "title": "Результат для студента 4 курса",
        "note": "Для магистратуры",
        "group": "8191-21",
        "solved": 0,
        "name": "Валерий Ершов",
        "year": "4",
        "telephone": "+7 903 165 7669",
        "id_vk": null,
        "linkVK": "http://vk.com/Jadon",
        "email": "ValeriErshov35@yahoo.com",
        "created_at": "2023-06-01T14:38:37.000Z"
    },
    {
        "id": 4,
        "event": "Договор",
        "title": "Договор 2",
        "note": "Для сотрудника",
        "group": "8191-22",
        "solved": 0,
        "name": "Глеб Казакова",
        "year": "1",
        "telephone": "+7 903 889 3716",
        "id_vk": null,
        "linkVK": "http://vk.com/Curt",
        "email": "GlebKazakova28@gmail.com",
        "created_at": "2023-06-01T14:38:37.000Z"
    },
    {
        "id": 5,
        "event": "Заявление",
        "title": "Договор 1",
        "note": "Для работки",
        "group": "8191-31",
        "solved": 0,
        "name": "Антон Лукьянова",
        "year": "1",
        "telephone": "+7 903 515 4890",
        "id_vk": null,
        "linkVK": "http://vk.com/Reilly",
        "email": "AntonLukyanova27@yahoo.com",
        "created_at": "2023-06-01T14:38:37.000Z"
    },
    {
        "id": 6,
        "event": "Результат",
        "title": "Договор 3",
        "note": "Для отпуска",
        "group": "8191-31",
        "solved": 0,
        "name": "Устин Максимова",
        "year": "4",
        "telephone": "+7 903 056 3979",
        "id_vk": null,
        "linkVK": "http://vk.com/Irving",
        "email": "UstinMaksimova50@yahoo.com",
        "created_at": "2023-06-01T14:38:37.000Z"
    },
    {
        "id": 7,
        "event": "Результат",
        "title": "Договор 2",
        "note": "Для сотрудника",
        "group": "8191-11",
        "solved": 0,
        "name": "Артур Соловьев",
        "year": "3",
        "telephone": "+7 903 350 2620",
        "id_vk": null,
        "linkVK": "http://vk.com/Hayden",
        "email": "ArturSolovyov80@yahoo.com",
        "created_at": "2023-06-01T14:38:37.000Z"
    },
    {
        "id": 8,
        "event": "Заявление",
        "title": "Договор 2",
        "note": "Для сотрудника",
        "group": "8191-22",
        "solved": 0,
        "name": "Саша Кузьмин",
        "year": "4",
        "telephone": "+7 903 605 0618",
        "id_vk": null,
        "linkVK": "http://vk.com/Carlos",
        "email": "Sacha.Kuzmin@hotmail.com",
        "created_at": "2023-06-01T14:38:37.000Z"
    },
    {
        "id": 9,
        "event": "Результат",
        "title": "Договор 1",
        "note": "Для работки",
        "group": "8191-21",
        "solved": 0,
        "name": "Михаил Афанасьева",
        "year": "3",
        "telephone": "+7 903 074 6120",
        "id_vk": null,
        "linkVK": "http://vk.com/Luz",
        "email": "MikhailAfanaseva@yahoo.com",
        "created_at": "2023-06-01T14:38:37.000Z"
    },
    {
        "id": 21,
        "event": "Результат",
        "title": "Результат 4 курс",
        "note": "Для стипендии",
        "group": "8191-22",
        "solved": 0,
        "name": "Сон Нгуен",
        "year": null,
        "telephone": null,
        "id_vk": 509715385,
        "linkVK": null,
        "email": null,
        "created_at": "2023-06-01T14:38:37.000Z"
    },
    {
        "id": 22,
        "event": "Результат",
        "title": "Результат для студента 4 курса",
        "note": "Для стипендии",
        "group": "8191-22",
        "solved": 0,
        "name": "Сон Нгуен",
        "year": null,
        "telephone": null,
        "id_vk": 509715385,
        "linkVK": null,
        "email": null,
        "created_at": "2023-06-01T15:05:48.000Z"
    },
    {
        "id": 23,
        "event": "Результат",
        "title": "Результат 4 курс",
        "note": "Для стипендии",
        "group": "8191-22",
        "solved": 0,
        "name": "Сон Нгуен",
        "year": null,
        "telephone": null,
        "id_vk": 509715385,
        "linkVK": null,
        "email": null,
        "created_at": "2023-06-01T15:07:28.000Z"
    }
];

export default data;