const data = [
    {
        "id": 10,
        "event": "Заявление",
        "title": "Заявление 3",
        "note": "Для учебы",
        "group": "8191-11",
        "solved": 1,
        "name": "Сергей Бирюкова",
        "year": "4",
        "telephone": "+7 903 019 4332",
        "id_vk": null,
        "linkVK": "http://vk.com/Ferne",
        "email": "SergeyBiryukova94@gmail.com",
        "created_at": "2023-06-01T14:38:37.000Z"
    },
    {
        "id": 11,
        "event": "Договор",
        "title": "Результат для студента 4 курса",
        "note": "Для магистратуры",
        "group": "8191-22",
        "solved": 1,
        "name": "Валериана Любимова",
        "year": "4",
        "telephone": "+7 903 677 0384",
        "id_vk": null,
        "linkVK": "http://vk.com/Saul",
        "email": "ValerianLyubimova71@gmail.com",
        "created_at": "2023-06-01T14:38:37.000Z"
    },
    {
        "id": 12,
        "event": "Заявление",
        "title": "Заявление 2",
        "note": "Для очисления",
        "group": "8191-22",
        "solved": 1,
        "name": "Игорь Галкина",
        "year": "5",
        "telephone": "+7 903 328 9738",
        "id_vk": null,
        "linkVK": "http://vk.com/Amelie",
        "email": "Raoul.Howell57@yahoo.com",
        "created_at": "2023-06-01T14:38:37.000Z"
    },
    {
        "id": 13,
        "event": "Результат",
        "title": "Результат для студента 2 курса",
        "note": "Для стипендии",
        "group": "8191-11",
        "solved": 1,
        "name": "Тимур Омаров",
        "year": "1",
        "telephone": "+7 903 216 6392",
        "id_vk": null,
        "linkVK": "http://vk.com/Hailie",
        "email": "Timur.Korolev38@hotmail.com",
        "created_at": "2023-06-01T14:38:37.000Z"
    },
    {
        "id": 14,
        "event": "Результат",
        "title": "Результат для студента 3 курса",
        "note": "Для стипендии",
        "group": "8191-21",
        "solved": 1,
        "name": "Иван Зотова",
        "year": "1",
        "telephone": "+7 903 238 7218",
        "id_vk": null,
        "linkVK": "http://vk.com/Brent",
        "email": "IvanZotova@gmail.com",
        "created_at": "2023-06-01T14:38:37.000Z"
    },
    {
        "id": 15,
        "event": "Заявление",
        "title": "Договор 3",
        "note": "Для отпуска",
        "group": "8191-21",
        "solved": 1,
        "name": "Константин Семёнова",
        "year": "1",
        "telephone": "+7 903 561 4623",
        "id_vk": null,
        "linkVK": "http://vk.com/Magdalen",
        "email": "KonstantinSemyonova32@yahoo.com",
        "created_at": "2023-06-01T14:38:37.000Z"
    },
    {
        "id": 16,
        "event": "Договор",
        "title": "Заявление 3",
        "note": "Для учебы",
        "group": "8191-21",
        "solved": 1,
        "name": "Василий Калинин",
        "year": "4",
        "telephone": "+7 903 517 6292",
        "id_vk": null,
        "linkVK": "http://vk.com/Leslie",
        "email": "WassilyKalinin91@hotmail.com",
        "created_at": "2023-06-01T14:38:37.000Z"
    },
    {
        "id": 17,
        "event": "Результат",
        "title": "Договор 2",
        "note": "Для сотрудника",
        "group": "8191-21",
        "solved": 1,
        "name": "Амир Ершова",
        "year": "2",
        "telephone": "+7 903 470 3531",
        "id_vk": null,
        "linkVK": "http://vk.com/Kasandra",
        "email": "Amir_Ershova79@yahoo.com",
        "created_at": "2023-06-01T14:38:37.000Z"
    },
    {
        "id": 18,
        "event": "Заявление",
        "title": "Договор 1",
        "note": "Для работки",
        "group": "8191-11",
        "solved": 1,
        "name": "Тимур Королев",
        "year": "4",
        "telephone": "+7 903 824 5914",
        "id_vk": null,
        "linkVK": "http://vk.com/Janessa",
        "email": "Timur.Korolev38@yahoo.com",
        "created_at": "2023-06-01T14:38:37.000Z"
    },
    {
        "id": 19,
        "event": "Результат",
        "title": "Договор 1",
        "note": "Для работки",
        "group": "8191-11",
        "solved": 1,
        "name": "Василий Симонов",
        "year": "4",
        "telephone": "+7 903 855 4501",
        "id_vk": null,
        "linkVK": "http://vk.com/Carmelo",
        "email": "VasilySimonov65@hotmail.com",
        "created_at": "2023-06-01T14:38:37.000Z"
    },
    {
        "id": 20,
        "event": "Результат",
        "title": "Результат для студента 3 курса",
        "note": "Для стипендии",
        "group": "8191-11",
        "solved": 1,
        "name": "Давид Матвеев",
        "year": "3",
        "telephone": "+7 903 710 0103",
        "id_vk": null,
        "linkVK": "http://vk.com/Jamey",
        "email": "David_Matveev40@hotmail.com",
        "created_at": "2023-06-01T14:38:37.000Z"
    }
];

export default data;