const data = [
    {
        "id": 1,
        "id_vk": 509715385,
        "avatar": "https://avatars.githubusercontent.com/u/4568",
        "name": "Сон Нгуен",
        "group": "8191-22",
        "year": "4",
        "telephone": "+7 903 045 6188",
        "email": "nminhson99@gmail.com",
        "note": "",
        "linkVK": "http://vk.com/WolfMSQG"
    },
    {
        "id": 2,
        "id_vk": null,
        "avatar": "https://avatars.githubusercontent.com/u/1",
        "name": "Семен Анисимов",
        "group": "8191-22",
        "year": "3",
        "telephone": "+7 903 045 6188",
        "email": "SemyonAnisimov@mail.ru",
        "note": "",
        "linkVK": "http://vk.com/Carmen"
    },
    {
        "id": 3,
        "id_vk": null,
        "avatar": "https://avatars.githubusercontent.com/u/3",
        "name": "Валериан Волков",
        "group": "8191-31",
        "year": "5",
        "telephone": "+7 903 897 4334",
        "email": "ValerianVolkov6@gmail.com",
        "note": "",
        "linkVK": "http://vk.com/Daniela"
    },
    {
        "id": 4,
        "id_vk": null,
        "avatar": "https://avatars.githubusercontent.com/u/4",
        "name": "Валерий Ершов",
        "group": "8191-31",
        "year": "5",
        "telephone": "+7 903 936 6608",
        "email": "ValeriErshov35@gmail.com",
        "note": "Отлично",
        "linkVK": "http://vk.com/Alessia"
    },
    {
        "id": 5,
        "id_vk": null,
        "avatar": "https://avatars.githubusercontent.com/u/7",
        "name": "Глеб Казакова",
        "group": "8191-11",
        "year": "1",
        "telephone": "+7 903 409 3136",
        "email": "GlebKazakova28@hotmail.com",
        "note": "",
        "linkVK": "http://vk.com/Sophie"
    },
    {
        "id": 6,
        "id_vk": null,
        "avatar": "https://avatars.githubusercontent.com/u/97165289",
        "name": "Антон Лукьянова",
        "group": "8191-21",
        "year": "1",
        "telephone": "+7 903 125 1020",
        "email": "AntonLukyanova27@hotmail.com",
        "note": "Отлично",
        "linkVK": "http://vk.com/Emely"
    },
    {
        "id": 7,
        "id_vk": null,
        "avatar": "https://avatars.githubusercontent.com/u/20",
        "name": "Устин Максимова",
        "group": "8191-11",
        "year": "2",
        "telephone": "+7 903 652 7061",
        "email": "UstinMaksimova50@yahoo.com",
        "note": "Отлично",
        "linkVK": "http://vk.com/Valentina"
    },
    {
        "id": 8,
        "id_vk": null,
        "avatar": "https://avatars.githubusercontent.com/u/22",
        "name": "Артур Соловьев",
        "group": "8191-11",
        "year": "1",
        "telephone": "+7 903 583 0549",
        "email": "ArturSolovyov80@yahoo.com",
        "note": "",
        "linkVK": "http://vk.com/Jamie"
    },
    {
        "id": 9,
        "id_vk": null,
        "avatar": "https://avatars.githubusercontent.com/u/23",
        "name": "Саша Кузьмин",
        "group": "8191-31",
        "year": "5",
        "telephone": "+7 903 372 4898",
        "email": "Sacha.Kuzmin@gmail.com",
        "note": "",
        "linkVK": "http://vk.com/Malinda"
    },
    {
        "id": 10,
        "id_vk": null,
        "avatar": "https://avatars.githubusercontent.com/u/25",
        "name": "Михаил Афанасьева",
        "group": "8191-11",
        "year": "5",
        "telephone": "+7 903 638 7590",
        "email": "MikhailAfanaseva@gmail.com",
        "note": "Хорошо",
        "linkVK": "http://vk.com/Rogers"
    },
    {
        "id": 11,
        "id_vk": null,
        "avatar": "https://avatars.githubusercontent.com/u/26",
        "name": "Сергей Бирюкова",
        "group": "8191-31",
        "year": "5",
        "telephone": "+7 903 899 7994",
        "email": "SergeyBiryukova94@gmail.com",
        "note": "",
        "linkVK": "http://vk.com/Vickie"
    },
    {
        "id": 12,
        "id_vk": null,
        "avatar": "https://avatars.githubusercontent.com/u/27",
        "name": "Валериана Любимова",
        "group": "8191-21",
        "year": "4",
        "telephone": "+7 903 969 0821",
        "email": "ValerianLyubimova71@gmail.com",
        "note": "",
        "linkVK": "http://vk.com/Mazie"
    },
    {
        "id": 13,
        "id_vk": null,
        "avatar": "https://avatars.githubusercontent.com/u/28",
        "name": "Станислав Фадеева",
        "group": "8191-11",
        "year": "4",
        "telephone": "+7 903 552 1010",
        "email": "StanislavFadeeva@hotmail.com",
        "note": "",
        "linkVK": "http://vk.com/Aurelia"
    },
    {
        "id": 14,
        "id_vk": null,
        "avatar": "https://avatars.githubusercontent.com/u/31",
        "name": "Игорь Галкина",
        "group": "8191-22",
        "year": "4",
        "telephone": "+7 903 810 3434",
        "email": "IgorGalkina@yahoo.com",
        "note": "",
        "linkVK": "http://vk.com/Sterling"
    },
    {
        "id": 15,
        "id_vk": null,
        "avatar": "https://avatars.githubusercontent.com/u/34",
        "name": "Иван Зотова",
        "group": "8191-31",
        "year": "3",
        "telephone": "+7 903 128 1384",
        "email": "IvanZotova@gmail.com",
        "note": "",
        "linkVK": "http://vk.com/Felix"
    },
    {
        "id": 16,
        "id_vk": null,
        "avatar": "https://avatars.githubusercontent.com/u/35",
        "name": "Константин Семёнова",
        "group": "8191-21",
        "year": "2",
        "telephone": "+7 903 100 1797",
        "email": "KonstantinSemyonova32@hotmail.com",
        "note": "",
        "linkVK": "http://vk.com/Chanelle"
    },
    {
        "id": 17,
        "id_vk": null,
        "avatar": "https://avatars.githubusercontent.com/u/37",
        "name": "Василий Калинин",
        "group": "8191-21",
        "year": "5",
        "telephone": "+7 903 935 0262",
        "email": "WassilyKalinin91@hotmail.com",
        "note": "",
        "linkVK": "http://vk.com/Arjun"
    },
    {
        "id": 18,
        "id_vk": null,
        "avatar": "https://avatars.githubusercontent.com/u/38",
        "name": "Амир Ершова",
        "group": "8191-22",
        "year": "1",
        "telephone": "+7 903 454 3209",
        "email": "Amir_Ershova79@hotmail.com",
        "note": "Хорошо",
        "linkVK": "http://vk.com/Napoleon"
    },
    {
        "id": 19,
        "id_vk": null,
        "avatar": "https://avatars.githubusercontent.com/u/45",
        "name": "Тимур Королев",
        "group": "8191-21",
        "year": "3",
        "telephone": "+7 903 782 3173",
        "email": "Timur.Korolev38@yahoo.com",
        "note": "Хорошо",
        "linkVK": "http://vk.com/Wilma"
    },
    {
        "id": 20,
        "id_vk": null,
        "avatar": "https://avatars.githubusercontent.com/u/69",
        "name": "Василий Симонов",
        "group": "8191-22",
        "year": "1",
        "telephone": "+7 903 107 8786",
        "email": "VasilySimonov65@gmail.com",
        "note": "Хорошо",
        "linkVK": "http://vk.com/Jonathan"
    },
    {
        "id": 21,
        "id_vk": null,
        "avatar": "https://avatars.githubusercontent.com/u/71",
        "name": "Давид Матвеев",
        "group": "8191-31",
        "year": "5",
        "telephone": "+7 903 269 3574",
        "email": "David_Matveev40@gmail.com",
        "note": "Отлично",
        "linkVK": "http://vk.com/Laurianne"
    }
]

export default data;